### ISSUE TITLE
please add mrzero Literatur submenue

### ISSUE THREAD

**Issue by mzaiss** [MRsources/MRzero-Core#20]
Endres, J., Dang, H., Glang, F., Loktyushin, A., Weinmüller, S., & Zaiss, M. (2022). Phase distribution graphs for differentiable and efficient simulations of arbitrary MRI sequences. In Joint Annual Meeting ISMRM-ESMRMB & ISMRT 31st Annual Meeting (ISMRM 2022). https://archive.ismrm.org/2022/0750.html

Loktyushin, A, Herz, K, Dang, N. MRzero - Automated discovery of MRI sequences using supervised learning. Magn Reson Med. 2021; 86: 709–724. https://doi.org/10.1002/mrm.28727

Dang, HN, Endres, J, Weinmüller, S, et al. MR-zero meets RARE MRI: Joint optimization of refocusing flip angles and neural networks to minimize T2-induced blurring in spin echo sequences. Magn Reson Med. 2023; 90(4): 1345-1362. https://doi.org/10.1002/mrm.29710

**Comment by J-Endres** [comment]
closed by 4773ad1528930fd8858f7797ee062c110bce374d
