### ISSUE TITLE
check sign in iso, pdg and adjoint!

### ISSUE THREAD

**Issue by mzaiss** [MRsources/MRzero-Core#33]
https://github.com/MRsources/MRzero-Core/blob/33c53a15df6650ca2d32c30aaf942c4b2d7bad8d/python/MRzeroCore/simulation/isochromat_sim.py#L190

- [x] iso
- [x] pdg
- [x] recon
- [x] all scripts using ifft
- [x] prepass

**Comment by mzaiss** [comment]
https://github.com/MRsources/MRzero-Core/blob/33c53a15df6650ca2d32c30aaf942c4b2d7bad8d/python/MRzeroCore/reconstruction.py#L95

**Comment by J-Endres** [comment]
The changes are implemented in the 0.2.9-dev branch, will merge after testing and updating all playground notebooks
