### ISSUE TITLE
plotting once and for all.

### ISSUE THREAD

**Issue by mzaiss** [MRsources/MRzero-Core#39]
lets put this in mr0. util and use it everywhere,  this is an used in phantom.plot
also fft everywhere!

def MR_imshow(data, *args, **kwargs):    # plt.imshow shows the matrix (x,y) as (col,rows)
    try: # Attempt to transpose data
        transposed_data = np.transpose(data) # util.MR_imshow transposes to (rows,col)
    except TypeError as e:
        print(f"Error transposing data: {e}")
        transposed_data=data
    plt.imshow(transposed_data, *args,origin="lower", **kwargs)  # also the origin is set to lower!

**Comment by J-Endres** [comment]
feec04e20f7d76c671ee5f6e8810ba5a1d0e245e

- [ ] make it work with torch (.cuda() .cpu())
- [ ] documentation
- [ ] naming?

**Comment by J-Endres** [comment]
Closed by af73f7f1d3dce04b5da5936a19b8120f0ab2df3a
