### ISSUE TITLE
VoxelGridPhantom.brainweb() access to "data" outside "with" context

### ISSUE THREAD

**Issue by o-dietrich** [MRsources/MRzero-Core#44]
In voxel_grid_phantom.py:178 (brainweb()), you are trying to get the FOV `size` from `data['FOV']`, but `data` is accessible only in the `with` context (l.155-159). Perhaps you could just move the 4 lines to set `size` into the `with` context above?

**Comment by o-dietrich** [comment]
Yes, I see an `AttributeError: 'NoneType' object has no attribute 'open'` (python 3.11.2, numpy 1.26.4). The variables (like `T1`, `PD`, ...) can of course be accessed outside the `with` statement, but not the opened file. The numpy documentation says "The underlying file descriptor is closed when exiting the ‘with’ block." (https://numpy.org/doc/stable/reference/generated/numpy.load.html).

**Comment by J-Endres** [comment]
Oh, my mistake, this is indeed not correct. Older test data had no "FOV" field, so this never triggered, but of course this must be moved within the `with` block.
It will be fixed (18b419033b3f1837c992aaeea778afeacdb7fb17) in the next version, thank you for your contribution!
