### ISSUE TITLE
Missing multiplication by tissue_map in generate_brainweb_phantoms()

### ISSUE THREAD

**Issue by o-dietrich** [MRsources/MRzero-Core#45]
In `generate_brainweb_phantoms()`, i.e. in [phantom](https://github.com/MRsources/MRzero-Core/tree/main/python/MRzeroCore/phantom)/[brainweb](https://github.com/MRsources/MRzero-Core/tree/main/python/MRzeroCore/phantom/brainweb)/\_\_init\_\_.py:154, a multiplication by `tissue_map` is missing for the generation of the T2 maps (`maps["T2_map"]`).

That should probably be 

> `maps["T2_map"] += tissue_data["T2"] * tissue_map * noise()`

instead of

>  `maps["T2_map"] += tissue_data["T2"] * noise()`

**Comment by J-Endres** [comment]
Thank you for this contribution, this is indeed an error. I will fix this and publish a new version within the next days.

**Comment by J-Endres** [comment]
Closed by b630c139f9d233f0b19a74a90d34cb51751ac52f
