### ISSUE TITLE
dtype error in main_pass.py:execute_graph()

### ISSUE THREAD

**Issue by o-dietrich** [MRsources/MRzero-Core#50]
Running the playground example "2D FLASH" (https://mrzero-core.readthedocs.io/en/latest/playground_mr0/mr0_FLASH_2D_seq.html) with a newly generated brainweb VoxelGridPhantom, i.e. for instance

>     obj_p = mr0.VoxelGridPhantom.brainweb('./brainweb/subject05_3T.npz') # instead of load_mat()

I get a

>     RuntimeError: expected m1 and m2 to have the same dtype, but got: double != float

in line 194 of main_pass.py, in execute_graph():

>     (dist_traj[:, :3] @ data.voxel_pos.T)

I can work around this (and a second `dtype` error) by manually changing `PD` and `voxel_pos` from `torch.float32` to `torch.float64`, i.e. by adding the two lines

>    obj_p.voxel_pos = obj_p.voxel_pos.to(torch.float64)
>    obj_p.PD = obj_p.PD.to(torch.float64)

after(!) `obj_p = obj_p.build()`, but  this doesn't appear to be a real fix. 

I guess either the `dtype` of the simulation data (after `build()`) should be taken into account (or converted?) in `execute_graph()` or `VoxelgridPhantom.brainweb()` should return data with the appropriate `dtype` or `build()` should provide data with consistent `dtype` (it seems that `torch.fft.fftfreq()` results in `float32` propagated to `voxel_pos`) or so ... please check!

**Comment by J-Endres** [comment]
All tensors are meant to be single precision (float32) - maybe the phantom size or something similar was float64, which propagated to `dist_traj`.
5d79febe2d1cda7316651d8a638bc77628a799c4 should fix this, the `VoxelGridPhantom` converts everything to `float32`:
https://github.com/MRsources/MRzero-Core/blob/5d79febe2d1cda7316651d8a638bc77628a799c4/python/MRzeroCore/phantom/voxel_grid_phantom.py#L106-L114

If the issue still persists, please re-open it
