### ISSUE TITLE
error in util.py:pulseq_plot(): missing conversion from list to np.array?

### ISSUE THREAD

**Issue by o-dietrich** [MRsources/MRzero-Core#51]
When using `pulseq_plot()` from util.py, I get the following error:

>       File "/.../lib/python3.11/site-packages/MRzeroCore/util.py", line 195, in pulseq_plot
>         t = adc.delay + [(x * adc.dwell)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     TypeError: unsupported operand type(s) for +: 'float' and 'list'

Changing this to

>             t = adc.delay + np.array([(x * adc.dwell)
>                         for x in range(0, int(adc.num_samples))])

(i.e. adding `np.array()`) seems to solve this.

**Comment by mzaiss** [comment]
the plotting depends heavily on the pulseq version.
older version can use the util you mentioned.

newer version require a two step way:

seq.plot(plot_now=False)
mr0.util.insert_signal_plot(seq,signal)
plt.show()


this is a bit hard to solve as it depends on the confusing versioning and
dev , main, pip differences of pypulseq



o-dietrich ***@***.***> schrieb am Mi., 10. Apr. 2024, 11:53:

**Comment by J-Endres** [comment]
As @mzaiss said, the plotting function is a modified version from the pulseq 1.2 plotting function with signal plots inserted:
https://github.com/imr-framework/pypulseq/blob/ebe1fa2a1358ff0028535c227906722ae484a1ec/pypulseq/Sequence/sequence.py#L435

It is only compatible with specific pulseq versions, which is why the new variant with injecting the signal after plotting was introduced. But this might not work with older pulseq versions that immediately plot and thus don't allow to change the plots afterwards.
@o-dietrich does the new approach to plotting work for you?

Leaving this issue open as this definitely should be reflected better in the documentation

**Comment by o-dietrich** [comment]
I fully agree about the confusing versioning of pypulseq ...

But I still don't understand how this line (taken from the current version of MRzero-Core, not from PyPulseq, where it no longer exists):
>     t = adc.delay + [(x * adc.dwell) for x in range(0, int(adc.num_samples))]
is supposed to work (and how it did so in pypulseq 1.2.x). 

If `adc.delay` is just a float, then I cannot add a list, can I? (Or should `adc.delay` also be a list? Then "adding" would work, but that wasn't the case in my examples.)

Syntactically, all of the following should work:

>     t = adc.delay + np.array([(x * adc.dwell) for x in range(0, int(adc.num_samples))])

>     t = [adc.delay + (x * adc.dwell) for x in range(0, int(adc.num_samples))]

>     t = [adc.delay,] + [(x * adc.dwell) for x in range(0, int(adc.num_samples))]

And all 3 variants do work in my current example (but not the original line, which raises the TypeError).

**Comment by J-Endres** [comment]
I was also surprised about this while looking into it... `adc.delay` is definitely not a list.

What might explain why this code worked with previous pypulseq versions (which it definitely did) is that those numbers are not python numbers but numpy scalars:

```python
>>> np.float32(1) + [2]
array([3.])
```
for example runs without crashing.

**Comment by o-dietrich** [comment]
So, the type of `adc.delay` may have been changed to `float` now, causing the error.

**Comment by o-dietrich** [comment]
> It is only compatible with specific pulseq versions, which is why the new variant with injecting the signal after plotting was introduced. But this might not work with older pulseq versions that immediately plot and thus don't allow to change the plots afterwards. @o-dietrich does the new approach to plotting work for you?

Both approaches seem to work (after correcting the numpy addition issue) and I do not see any obvious differences.

**Comment by mzaiss** [comment]
I think the newer plots have the ADC phase plotted,  our 1.2. based
plotting function not as this came with 1.4 i think



o-dietrich ***@***.***> schrieb am Mi., 10. Apr. 2024, 15:07:

**Comment by o-dietrich** [comment]
> I think the newer plots have the ADC phase plotted, our 1.2. based plotting function not as this came with 1.4 i think 

Right, I can confirm this difference. (On the other hand, the "filled" RF pulse shapes are not so bad with the mrzero version.)

**Comment by mzaiss** [comment]
thanks! that was my personal contribution.
especially helpful for block pulses :)

o-dietrich ***@***.***> schrieb am Mi., 10. Apr. 2024, 15:34:

**Comment by J-Endres** [comment]
fixed by a8b10cd7e3952e3695b903436ec3c33cf461b6e8
