### ISSUE TITLE
3D phantom load load_mat currently not possible directly

### ISSUE THREAD

**Issue by mzaiss** [MRsources/MRzero-Core#55]
phantom = mr0.VoxelGridPhantom.load_mat('low_field_phantom.mat')
currently expects a phantom of shape (x,y,p)  with dimensions (nx,ny,5) where p is [PD,T1, T2,B0,B1)

if phantom.mat contains a phantom of shape (x,y,z,p)  with dimensions (nx,ny,nz,5) where p is [PD,T1, T2,B0,B1)
it is not loaded correctly as 3D

a workaround is: 

phantom = mr0.VoxelGridPhantom.load_mat('phantom.mat') #(nx,ny,nz,5)
phantom.B0 = phantom.B0.squeeze().permute(1,2,0)
phantom.PD = phantom.PD.squeeze().permute(1,2,0)
phantom.D = phantom.D.squeeze().permute(1,2,0)
phantom.B1=phantom.B1[:,:,:,0,:].permute(0,2,3,1)
phantom.coil_sens=phantom.coil_sens[:,:,:,0,:].permute(0,2,3,1)
phantom.T1 = phantom.T1.squeeze().permute(1,2,0)
phantom.T2 = phantom.T2.squeeze().permute(1,2,0)
phantom.T2dash = phantom.T2dash.squeeze().permute(1,2,0)

would be great to generally make 3D possible

**Comment by J-Endres** [comment]
Fixed by 3663095a614262ee176b6dd25eda801575a92785
3D matlab data can now be loaded directly
