### ISSUE TITLE
Any way to simulate velocity?

### ISSUE THREAD

**Issue by dangom** [MRsources/MRzero-Core#66]
Was wondering whether it'd be possible to simulate the impact of velocity selective pulses on the magnetization.
I imagine the phantom class would have to contain that info, and the sim would have to figure out how to take that into account.

**Comment by J-Endres** [comment]
Great question. After reading about this technique it seems feasible - but to me it sounds like its necessary to simulate flow to get meaningful results. Do you have data or a model of what you want to put in the virtual scanner so to speak?
