### ISSUE TITLE
Pulseq Importer ADC phase

### ISSUE THREAD

**Issue by J-Endres** [MRsources/MRzero-Core#7]
Pulseq and MR0 defines adc phase differently:
MR0 applies exp(i*phase) to the signal and uses for the signal the same coordinate system as for the magnetization. This requires using an ADC phase of pi - rf_phase in the case of e.g. a FLASH sequence.
Pulseq uses a definition where in the FLASH rf spoiling is realized by adc_phase = rf_phase.

This means that when importing pulseq .seq files, we should apply mr0_adc_phase = pi - seq_adc_phase

I can't find this conversion in the code right now, we should test if this is actually handled correctly by looking at / simulating a .seq file with phase cycling.

**Comment by SWeinmueller** [comment]
I think we solve this directly in the interpreter:
seq = Sequence()
for tmp_rep in tmp_seq:
    rep = seq.new_rep(tmp_rep[0])
    rep.pulse.angle = torch.tensor(tmp_rep[1].angle, dtype=torch.float)
    rep.pulse.phase = torch.tensor(tmp_rep[1].phase, dtype=torch.float)
    is_refoc = abs(tmp_rep[1].angle) > 1.6  # ~91°
    rep.pulse.usage = PulseUsage.REFOC if is_refoc else PulseUsage.EXCIT

    offset = 0
    for block in tmp_rep[2]:
        if isinstance(block, Spoiler):
            rep.event_time[offset] = block.duration
            rep.gradm[offset, :] = torch.tensor(block.gradm)
            offset += 1
        else:
            assert isinstance(block, Adc)
            num = len(block.event_time)
            rep.event_time[offset:offset+num] = torch.tensor(block.event_time)
            rep.gradm[offset:offset+num, :] = torch.tensor(block.gradm)
            **rep.adc_phase[offset:offset+num] = np.pi/2 - block.phase**
            rep.adc_usage[offset:offset+num] = 1
            offset += num
    assert offset == tmp_rep[0]

**Comment by J-Endres** [comment]
You are right, it is also taken care of in MRzero Core
https://github.com/MRsources/MRzero-Core/blob/d3f76c5a7d2e41f3bfc14b0f8280b349fd72b82f/python/MRzeroCore/sequence.py#L385
That is probably also the correct place to do it.
