### ISSUE TITLE
SMS simulation

### ISSUE THREAD

**Issue by aTrotier** [MRsources/MRzero-Core#77]
Hi, 
thank you for this great tool. I would like to use it to simulate a SMS sequence.

Do you have advices / examples ? Especially about the 3D phantom / Field-of-view information ?

**Comment by mzaiss** [comment]
This is currently not possible as we assume instantaneous pulses.
For shaped pulses Koma, MRIlab or Jemris is better

aTrotier ***@***.***> schrieb am Mi., 30. Okt. 2024, 15:21:

**Comment by aTrotier** [comment]
Thanks :)
